version: '3'
services:

  harpia_ws:
    container_name: projeto_final2
    image: ghcr.io/ufrj-nautilus/harpia_ws:main
    pull_policy: always
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime
      - ./src/:/root/catkin_ws/src/
    network_mode: host
    stdin_open: true
    tty: true